# Generated by Django 3.1 on 2020-09-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('author', models.CharField(default='Random', max_length=40)),
                ('isbn', models.CharField(max_length=12)),
                ('discription', models.TextField()),
                ('copies', models.IntegerField(default=50)),
                ('available', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('language', models.CharField(choices=[('English', 'English'), ('Marathi', 'Marathi'), ('Hindi', 'Hindi')], max_length=7)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('reg_no', models.CharField(default='***', max_length=15)),
                ('branch', models.CharField(choices=[('IT', 'IT'), ('CSE', 'CSE'), ('MECH', 'MECH'), ('PROD', 'PROD'), ('CHEM', 'CHEM'), ('CIVIL', 'CIVIL'), ('TEXT', 'TEXT'), ('EXTC', 'EXTC'), ('ELECT', 'ELECT'), ('INSTRU', 'INSTRU')], default='IT', max_length=6)),
                ('assign_date', models.DateField(verbose_name='book assign date')),
                ('due_date', models.DateField(verbose_name='Due on')),
                ('due_fine', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book_assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
        migrations.CreateModel(
            name='fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=15)),
                ('branch', models.CharField(choices=[('IT', 'IT'), ('CSE', 'CSE'), ('MECH', 'MECH'), ('PROD', 'PROD'), ('CHEM', 'CHEM'), ('CIVIL', 'CIVIL'), ('TEXT', 'TEXT'), ('EXTC', 'EXTC'), ('ELECT', 'ELECT'), ('INSTRU', 'INSTRU')], max_length=6)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.student')),
            ],
        ),
    ]
