# Generated by Django 3.1 on 2020-09-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200926_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Marathi', 'Marathi'), ('Hindi', 'Hindi')], default='English', max_length=7),
        ),
    ]
